---
version: '3.7'

volumes:
  db-data:

services:
  db:
    networks:
      - default
    image: postgres:15-alpine
    ports:
      - '54323:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: local
    volumes:
      - db-data:/var/lib/postgresql/data
